[package]
name = "fav"
version = "0.3.0"
edition = "2024"
license = "GPL-3.0-only"
description = "Speed-dial for files and folders."
readme = "README.md"
keywords = ["cli", "productivity", "files", "paths", "tui"]
categories = ["command-line-utilities", "filesystem"]
repository = "https://github.com/dan-hart/fav"
homepage = "https://github.com/dan-hart/fav"
documentation = "https://docs.rs/fav"

[dependencies]
anyhow = "1.0.95"
fs2 = "0.4.3"
tempfile = "3.10.1"
clap = { version = "4.5.28", features = ["derive"] }
crossterm = "0.28.1"
directories = "5.0.1"
ratatui = "0.26.3"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.137"
shellexpand = "3.1.0"

[dev-dependencies]
assert_cmd = "2.0.14"
predicates = "3.1.0"
tempfile = "3.10.1"

[features]
coverage = []
